-- ============================================================
--  Perfume Store - PostgreSQL schema
--  Same logical model as the MySQL script, translated to Postgres.
--  Target: any free Postgres host (Neon, Supabase, Aiven, Render).
--
--  Type mapping used throughout:
--    INT UNSIGNED AUTO_INCREMENT -> INTEGER GENERATED BY DEFAULT AS IDENTITY
--    TINYINT(1)                  -> SMALLINT   (kept numeric, NOT boolean, so
--                                               the PHP checks  status == 1
--                                               and  status == '1'  still pass)
--    DATETIME / TIMESTAMP        -> TIMESTAMPTZ
--    ON UPDATE CURRENT_TIMESTAMP -> trigger (defined at the bottom)
-- ============================================================

DROP TABLE IF EXISTS order_item CASCADE;
DROP TABLE IF EXISTS orders     CASCADE;
DROP TABLE IF EXISTS cart       CASCADE;
DROP TABLE IF EXISTS perfumes   CASCADE;
DROP TABLE IF EXISTS customer   CASCADE;

-- ------------------------------------------------------------
-- customer : site users. admin_check = 1 unlocks /admin.
-- Referenced by cart.user_id and orders.user_id.
-- ------------------------------------------------------------
CREATE TABLE customer (
    id          INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    username    VARCHAR(50)  NOT NULL,
    password    VARCHAR(255) NOT NULL,
    name        VARCHAR(100) NOT NULL,
    email       VARCHAR(150) NOT NULL,
    contacts    VARCHAR(30),
    address     VARCHAR(255),
    dob         DATE,
    admin_check SMALLINT     NOT NULL DEFAULT 0,
    -- Password reset. Only a SHA-256 hash of the reset token is ever stored,
    -- the same way the password itself is never stored in reversible form --
    -- a stolen copy of this table cannot be used to reset anyone's password.
    reset_token_hash    CHAR(64),
    reset_token_expires TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_customer          PRIMARY KEY (id),
    CONSTRAINT uq_customer_username UNIQUE (username),
    CONSTRAINT uq_customer_email    UNIQUE (email),
    CONSTRAINT ck_customer_admin    CHECK (admin_check IN (0, 1))
);

-- ------------------------------------------------------------
-- perfumes : product catalogue.
--   status   1 = published (visible on the storefront)
--   trending 1 = shown in the home-page carousel
-- name is UNIQUE because display-perfume.php?name=... resolves a
-- single product by its name.
-- ------------------------------------------------------------
CREATE TABLE perfumes (
    id            INTEGER       GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(150)  NOT NULL,
    perfume_notes TEXT,
    description   TEXT,
    volume        VARCHAR(30),
    qty           INTEGER       NOT NULL DEFAULT 0,
    image_path    VARCHAR(255),
    price         NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    trending      SMALLINT      NOT NULL DEFAULT 0,
    status        SMALLINT      NOT NULL DEFAULT 1,
    -- A time-boxed discount. discount_percent = 0 means no discount at all,
    -- regardless of the dates -- the window only matters once a percentage
    -- is actually set. price itself never changes: it is always the
    -- original price, and the discounted price is computed from it.
    discount_percent   SMALLINT    NOT NULL DEFAULT 0,
    discount_starts_at TIMESTAMPTZ,
    discount_ends_at   TIMESTAMPTZ,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_perfumes          PRIMARY KEY (id),
    CONSTRAINT uq_perfumes_name     UNIQUE (name),
    CONSTRAINT ck_perfumes_price    CHECK (price >= 0),
    CONSTRAINT ck_perfumes_qty      CHECK (qty >= 0),
    CONSTRAINT ck_perfumes_trending CHECK (trending IN (0, 1)),
    CONSTRAINT ck_perfumes_status   CHECK (status   IN (0, 1)),
    CONSTRAINT ck_perfumes_discount_percent CHECK (discount_percent BETWEEN 0 AND 90),
    CONSTRAINT ck_perfumes_discount_window CHECK (
        discount_ends_at IS NULL OR discount_starts_at IS NULL OR discount_ends_at > discount_starts_at
    )
);

CREATE INDEX idx_perfumes_status   ON perfumes (status);
CREATE INDEX idx_perfumes_trending ON perfumes (trending, status);
-- Supports the brand pages' case-insensitive  name ILIKE '%dior%'  scans.
CREATE INDEX idx_perfumes_name_lower ON perfumes (LOWER(name));

-- ------------------------------------------------------------
-- cart : one live row per (customer, perfume).
-- The UNIQUE pair enforces at DB level what cart-function.php
-- checks in PHP before inserting.
-- Both parents CASCADE: a cart line has no meaning without them.
-- ------------------------------------------------------------
CREATE TABLE cart (
    id          INTEGER     GENERATED BY DEFAULT AS IDENTITY,
    user_id     INTEGER     NOT NULL,
    perfume_id  INTEGER     NOT NULL,
    perfume_qty INTEGER     NOT NULL DEFAULT 1,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_cart              PRIMARY KEY (id),
    CONSTRAINT uq_cart_user_perfume UNIQUE (user_id, perfume_id),
    CONSTRAINT fk_cart_user         FOREIGN KEY (user_id)
        REFERENCES customer (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_cart_perfume      FOREIGN KEY (perfume_id)
        REFERENCES perfumes (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT ck_cart_qty          CHECK (perfume_qty > 0)
);

-- ------------------------------------------------------------
-- orders : order header. tracking_no is the public handle used by
-- order-details.php?trackid=... so it is UNIQUE.
--   status 0=Processing 1=Completed 2=Shipped 3=Delivered 4=Cancelled
-- user_id is NULL for a guest checkout (no account was created) and
-- RESTRICT for a real customer: order history must survive, so a
-- customer who has ordered cannot be hard-deleted. name/email/
-- contacts/address are stored directly on the row either way, so a
-- guest order is fully self-contained without a customer row.
-- ------------------------------------------------------------
CREATE TABLE orders (
    id           INTEGER       GENERATED BY DEFAULT AS IDENTITY,
    tracking_no  VARCHAR(40)   NOT NULL,
    user_id      INTEGER,
    name         VARCHAR(100)  NOT NULL,
    email        VARCHAR(150)  NOT NULL,
    contacts     VARCHAR(30),
    address      VARCHAR(255),
    zipcode      VARCHAR(15),
    total_price  NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    payment_mode VARCHAR(30)   NOT NULL DEFAULT 'COD',
    payment_id   VARCHAR(50),
    status       SMALLINT      NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_orders          PRIMARY KEY (id),
    CONSTRAINT uq_orders_tracking UNIQUE (tracking_no),
    CONSTRAINT fk_orders_user     FOREIGN KEY (user_id)
        REFERENCES customer (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT ck_orders_status   CHECK (status BETWEEN 0 AND 4),
    CONSTRAINT ck_orders_total    CHECK (total_price >= 0)
);

CREATE INDEX idx_orders_user   ON orders (user_id, created_at);
CREATE INDEX idx_orders_status ON orders (status);

-- ------------------------------------------------------------
-- order_item : order lines. price is copied at purchase time so
-- later catalogue price edits do not rewrite history.
--   order_id   CASCADE  - lines belong to their header
--   perfume_id RESTRICT - a perfume that was ever sold cannot be
--                         hard-deleted; unpublish it (status = 0)
-- ------------------------------------------------------------
CREATE TABLE order_item (
    id          INTEGER       GENERATED BY DEFAULT AS IDENTITY,
    order_id    INTEGER       NOT NULL,
    perfume_id  INTEGER       NOT NULL,
    perfume_qty INTEGER       NOT NULL DEFAULT 1,
    price       NUMERIC(10,2) NOT NULL DEFAULT 0.00,

    CONSTRAINT pk_order_item         PRIMARY KEY (id),
    CONSTRAINT uq_order_item_line    UNIQUE (order_id, perfume_id),
    CONSTRAINT fk_order_item_order   FOREIGN KEY (order_id)
        REFERENCES orders (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_order_item_perfume FOREIGN KEY (perfume_id)
        REFERENCES perfumes (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT ck_order_item_qty     CHECK (perfume_qty > 0),
    CONSTRAINT ck_order_item_price   CHECK (price >= 0)
);

CREATE INDEX idx_order_item_order   ON order_item (order_id);
CREATE INDEX idx_order_item_perfume ON order_item (perfume_id);

-- ------------------------------------------------------------
-- Postgres has no "ON UPDATE CURRENT_TIMESTAMP", so orders.updated_at
-- is maintained by a trigger instead.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_orders_updated_at
    BEFORE UPDATE ON orders
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
