BEGIN;

-- ============================================================
--  Perfume Store - Migration 07: More Perfumes
--  Adds 57 more products (ids 72-128).
--
--  PHOTOGRAPHY: the images originally fetched for this batch by an
--  automated scraper turned out to be wrong or unrelated for all 57
--  products -- see 08_migration_fix_mismatched_images.sql for the full
--  incident. image_path values here have since been replaced: verified
--  official product photography where freely available, and tasteful
--  unbranded editorial/stock photography (never the specific branded
--  bottle) for houses whose official photography is not freely licensed
--  (Creed, Rasasi, Rayhaan, Afnan) -- see
--  09_migration_restore_images.sql for databases where this file already
--  ran with the blanked (Photography pending) paths from migration 08.
-- ============================================================

INSERT INTO perfumes
    (id, name, perfume_notes, description, volume, qty, image_path, price, trending, status)
VALUES
    (72, 'Givenchy Gentleman Reserve Privee', 'Top: Bergamot. Heart: Iris, Chestnut. Base: Whiskey, Wood, Amber.', 'A refined, boozy iris fragrance perfect for formal occasions.', '100 ml', 15, 'givenchy_gentleman_reserve_privee.jpg', 13200.00, 0, 1),
    (73, 'Givenchy L Interdit', 'Top: Pear, Bergamot. Heart: Tuberose, Orange Blossom, Jasmine. Base: Patchouli, Vanilla, Ambroxan.', 'A bold and elegant white floral fragrance.', '80 ml', 20, 'givenchy_linterdit.jpg', 15000.00, 0, 1),
    (74, 'Jean Paul Gaultier Le Male Le Parfum', 'Top: Cardamom. Heart: Lavender, Iris. Base: Vanilla, Oriental notes, Woodsy notes.', 'An intense, spicy, and woody vanilla interpretation of the classic.', '125 ml', 25, 'jean_paul_gaultier_le_male_le_parfum.jpg', 15600.00, 0, 1),
    (75, 'Jean Paul Gaultier La Belle', 'Top: Pear. Heart: Vetiver. Base: Vanilla.', 'An ultra-sensual and sweet vanilla-pear composition.', '100 ml', 18, 'jean_paul_gaultier_la_belle.jpg', 13800.00, 0, 1),
    (76, 'Prada L Homme Intense', 'Top: Iris. Heart: Amber, Patchouli. Base: Tonka Bean, Sandalwood, Leather.', 'A richer, darker, and more intense version of the powdery classic.', '100 ml', 12, 'prada_lhomme_intense.jpg', 16800.00, 0, 1),
    (77, 'Prada Amber Pour Homme', 'Top: Mandarin Orange, Neroli, Cardamom, Bergamot. Heart: Orange Blossom, Musk, Vetiver, Geranium, Myrrh. Base: Labdanum, Leather, Sandalwood, Tonka Bean, Patchouli, Vanilla, Saffron.', 'A soapy, clean, and luxurious barbershop scent.', '100 ml', 10, 'prada_amber_pour_homme.jpg', 13200.00, 0, 1),
    (78, 'Giorgio Armani Acqua Di Gio Profondo', 'Top: Sea Notes, Aquozone, Bergamot, Green Mandarin. Heart: Rosemary, Cypress, Lavender, Mastic. Base: Mineral notes, Musk, Patchouli, Amber.', 'A deep dive into the ocean. Fresh, aquatic, and aromatic.', '125 ml', 30, 'giorgio_armani_acqua_di_gio_profondo.jpg', 16200.00, 0, 1),
    (79, 'Giorgio Armani Code Absolu', 'Top: Green Mandarin, Apple. Heart: Nutmeg, Orange Blossom, Carrot Seeds. Base: Vanilla, Tonka Bean, Suede, Woody Notes.', 'Warm, spicy, and seductively sweet.', '110 ml', 15, 'giorgio_armani_code_absolu.jpg', 16800.00, 0, 1),
    (80, 'Paco Rabanne 1 Million Elixir', 'Top: Apple, Davana. Heart: Damask Rose, Osmanthus, Cedar. Base: Vanilla Absolute, Tonka Bean, Patchouli.', 'The intensity of vanilla and tonka bean in a powerful blend.', '100 ml', 25, 'paco_rabanne_1_million_elixir.jpg', 14400.00, 0, 1),
    (81, 'Paco Rabanne Phantom', 'Top: Lavender, Lemon Zest, Amalfi Lemon. Heart: Lavender, Apple, Smoke. Base: Vanilla, Lavender, Vetiver.', 'A futuristic aromatic fragrance born from the clash between luxury craftmanship and new tech.', '100 ml', 30, 'paco_rabanne_phantom.jpg', 13800.00, 0, 1),
    (82, 'Kilian Good Girl Gone Bad', 'Top: Osmanthus, Jasmine, May Rose. Heart: Indian Tuberose, Narcissus. Base: Amber, Cedar.', 'A luscious, uninhibited floral whirlwind.', '50 ml', 8, 'kilian_good_girl_gone_bad.jpg', 30000.00, 0, 1),
    (83, 'Afnan Supremacy Silver', 'Top: Apple, Bergamot, Blackcurrant, Pineapple. Heart: Rose, Birch, Moroccan Jasmine, Patchouli. Base: Oakmoss, Musk, Ambergris, Vanilla.', 'A fruity, woody fragrance with a recognizable pineapple-birch smokiness.', '100 ml', 25, 'afnan_supremacy_silver.jpg', 4200.00, 0, 1),
    (84, 'Afnan Supremacy In Heaven', 'Top: Mandarin Orange, Bergamot. Heart: Green Tea, Blackcurrant. Base: Sandalwood, Woodsy Notes, Musk.', 'A fresh and uplifting scent inspired by alpine air and green tea.', '100 ml', 20, 'afnan_supremacy_in_heaven.jpg', 4200.00, 0, 1),
    (85, 'Afnan Modest Une', 'Top: Pepper, Lavender, Mint, Citrus. Heart: Eucalyptus, Frankincense, Vetiver. Base: Cedarwood, Musk.', 'An aromatic, spicy, and woody powerhouse of freshness.', '100 ml', 15, 'afnan_modest_une.jpg', 4560.00, 0, 1),
    (86, 'Afnan 9AM Dive', 'Top: Mint, Lemon, Pink Pepper, Black Currant. Heart: Apple, Incense, Cedar. Base: Ginger, Sandalwood, Patchouli, Jasmine.', 'A versatile fresh blue fragrance suitable for day and night.', '100 ml', 40, 'afnan_9am_dive.jpg', 3600.00, 0, 1),
    (87, 'Afnan Historic Olmeda', 'Top: Pink Pepper, Cardamom, Juniper, Grapefruit. Heart: Bergamot, Cedar, Nutmeg, Jasmine. Base: Patchouli, Apple, Ambergris, Musk.', 'A refined woody spicy fragrance with a lively opening.', '100 ml', 12, 'afnan_historic_olmeda.jpg', 5400.00, 0, 1),
    (88, 'Jean Paul Gaultier Le Male', 'Top: Lavender, Mint, Cardamom, Bergamot. Heart: Cinnamon, Orange Blossom. Base: Vanilla, Tonka Bean, Amber, Sandalwood.', 'The iconic sailor torso bottle. A barbershop vanilla classic that redefined mens fragrance.', '125 ml', 35, 'jean_paul_gaultier_le_male.jpg', 11400.00, 0, 1),
    (89, 'Jean Paul Gaultier Scandal Pour Homme Le Parfum', 'Top: Geranium. Heart: Tonka Bean. Base: Sandalwood.', 'An intense, woody amber scent that commands attention.', '100 ml', 20, 'jean_paul_gaultier_scandal_pour_homme_le_parfum.jpg', 13800.00, 0, 1),
    (90, 'Jean Paul Gaultier Le Beau', 'Top: Bergamot. Heart: Coconut. Base: Tonka Bean.', 'A fresh, sweet, and seductive coconut wood fragrance.', '125 ml', 30, 'jean_paul_gaultier_le_beau.jpg', 12000.00, 0, 1),
    (91, 'Jean Paul Gaultier Classique', 'Top: Orange Blossom, Star Anise, Rose, Pear, Bergamot. Heart: Ylang-Ylang, Ginger, Orchid, Iris. Base: Vanilla, Amber, Musk.', 'A timeless symbol of seduction and extreme sensuality.', '100 ml', 15, 'jean_paul_gaultier_classique.jpg', 13200.00, 0, 1),
    (92, 'Jean Paul Gaultier Le Male Elixir', 'Top: Lavender, Mint. Heart: Vanilla, Benzoin. Base: Honey, Tonka Bean, Tobacco.', 'A fiery, rich, and honeyed take on the Le Male DNA.', '125 ml', 25, 'jean_paul_gaultier_le_male_elixir.jpg', 15600.00, 0, 1),
    (93, 'Givenchy Pi', 'Top: Mandarin Orange, Tarragon, Rosemary, Basil. Heart: Anise, Neroli, Geranium. Base: Vanilla, Almond, Tonka Bean, Benzoin.', 'An excellent vanilla and almond fragrance for the intellectual explorer.', '100 ml', 18, 'givenchy_pi.jpg', 10800.00, 0, 1),
    (94, 'Givenchy Gentleman Eau de Parfum', 'Top: Black Pepper, Lavender, Bergamot. Heart: Orris, Cloves, Cinnamon. Base: Black Vanilla Husk, Tolu Balsam, Tonka Bean.', 'A sophisticated, spicy, and powdery iris fragrance for evenings.', '100 ml', 22, 'givenchy_gentleman_eau_de_parfum.jpg', 12600.00, 0, 1),
    (95, 'Givenchy Xeryus Rouge', 'Top: Cactus, Kumquat, Tarragon. Heart: Pimento, African Geranium. Base: Sandalwood, Cedar, White Musk.', 'A passionate, fiery red classic from 1995.', '100 ml', 10, 'givenchy_xeryus_rouge.jpg', 11400.00, 0, 1),
    (96, 'Givenchy Amarige', 'Top: Orange Blossom, Peach, Plum, Neroli. Heart: Tuberose, Mimosa, Gardenia, Ylang-Ylang. Base: Sandalwood, Woody Notes, Vanilla, Amber.', 'A radiant, joyous floral bouquet.', '100 ml', 12, 'givenchy_amarige.jpg', 12000.00, 0, 1),
    (97, 'Givenchy L Interdit Rouge', 'Top: Ginger, Blood Orange. Heart: Tuberose, Jasmine. Base: Sandalwood, Patchouli, Vetiver.', 'A spicy, thrilling reinterpretation of the iconic white floral.', '80 ml', 15, 'givenchy_l_interdit_rouge.jpg', 15000.00, 0, 1),
    (98, 'Paco Rabanne Black XS', 'Top: Lemon, Sage, Marigold. Heart: Praline, Cinnamon, Tolu Balsam, Black Cardamom. Base: Brazilian Rosewood, Patchouli, Black Amber.', 'A rocknroll fragrance with a sweet and spicy praline heart.', '100 ml', 20, 'paco_rabanne_black_xs.jpg', 10200.00, 0, 1),
    (99, 'Paco Rabanne Olympea', 'Top: Water Jasmine, Green Mandarin, Ginger flower. Heart: Vanilla, Salt. Base: Ambergris, Cashmere Wood, Sandalwood.', 'A salty-vanilla sensation designed for a modern goddess.', '80 ml', 25, 'paco_rabanne_olympea.jpg', 11400.00, 0, 1),
    (100, 'Paco Rabanne Pure XS', 'Top: Ginger, Thyme, Grapefruit, Bergamot. Heart: Vanilla, Liquor, Cinnamon, Leather, Apple. Base: Myrrh, Sugar, Cedar.', 'An untamed oriental on fire.', '100 ml', 18, 'paco_rabanne_pure_xs.jpg', 10800.00, 0, 1),
    (101, 'Paco Rabanne Lady Million', 'Top: Raspberry, Neroli, Amalfi Lemon. Heart: Jasmine, African Orange Flower, Gardenia. Base: White Honey, Patchouli, Amber.', 'A glamorous, ultra-feminine white floral and honey composition.', '80 ml', 22, 'paco_rabanne_lady_million.jpg', 12600.00, 0, 1),
    (102, 'Paco Rabanne 1 Million Parfum', 'Top: Tuberose, Monoi Oil, Labdanum. Heart: Leather, Cashmeran, Salt. Base: Pine, Ambergris.', 'A sun-drenched floral leather built for the spotlight.', '100 ml', 20, 'paco_rabanne_1_million_parfum.jpg', 13800.00, 0, 1),
    (103, 'Mancera Roses Vanille', 'Top: Lemon, Water Notes. Heart: Rose, Sugar. Base: Vanilla, Sugar, White Musk, Cedar.', 'An intoxicating blend of sugary sweet roses and vanilla.', '120 ml', 30, 'mancera_roses_vanille.jpg', 17400.00, 0, 1),
    (104, 'Mancera Aoud Lemon Mint', 'Top: Lemon, Coriander, Pepper, Almond. Heart: Egyptian Jasmine, Patchouli, Agarwood. Base: Leather, Amber, Vetiver, Musk, Vanilla.', 'A refreshing, unique take on oud with a burst of lemon and mint.', '120 ml', 25, 'mancera_aoud_lemon_mint.jpg', 18000.00, 0, 1),
    (105, 'Mancera Holidays', 'Top: Coconut, Bergamot. Heart: Tiare Flower, Ylang-Ylang, Sea Notes. Base: Vanilla Pod, Sandalwood, White Musk.', 'A tropical vacation in a bottle.', '120 ml', 15, 'mancera_holidays.jpg', 16800.00, 0, 1),
    (106, 'Mancera Coco Vanille', 'Top: Coconut, White Peach. Heart: Tiare Flower, Ylang-Ylang. Base: Madagascar Vanilla, White Musk, Woody Notes.', 'Creamy coconut and vanilla that smells like expensive sunscreen.', '120 ml', 20, 'mancera_coco_vanille.jpg', 16800.00, 0, 1),
    (107, 'Mancera Black Gold', 'Top: Lavender, Cinnamon, Nutmeg, Agarwood. Heart: Violet, Rose, Jasmine, Patchouli. Base: Leather, Woody Notes, White Musk, Amber.', 'A complex, bold, and luxurious spicy floral leather.', '120 ml', 18, 'mancera_black_gold.jpg', 19200.00, 0, 1),
    (108, 'Creed Millesime Imperial', 'Top: Fruity Notes, Sea Salt. Heart: Iris, Mandarin Orange, Sicilian Lemon, Bergamot. Base: Musk, Woody Notes, Sea Notes.', 'A golden, salty, fruity fragrance fit for royalty.', '100 ml', 15, 'creed_millesime_imperial.jpg', 46800.00, 0, 1),
    (109, 'Creed Virgin Island Water', 'Top: Coconut, Lime, White Bergamot. Heart: Ginger, Ylang-Ylang, Indian Jasmine. Base: White Rum, Sugar Cane, Musk.', 'An irresistible tropical cocktail.', '100 ml', 12, 'creed_virgin_island_water.jpg', 49800.00, 0, 1),
    (110, 'Creed Royal Oud', 'Top: Pink Pepper, Lemon, Sicilian Bergamot. Heart: Cedar, Angelica, Galbanum. Base: Sandalwood, Agarwood, Musk.', 'A sophisticated, dry, and majestic woody scent.', '100 ml', 10, 'creed_royal_oud.jpg', 54000.00, 0, 1),
    (111, 'Creed Himalaya', 'Top: Calabrian bergamot, Grapefruit, Sicilian Lemon. Heart: Sandalwood. Base: Musk, Ambergris, Cedar.', 'A crisp, fresh, and metallic scent inspired by the Tibetan mountains.', '100 ml', 8, 'creed_himalaya.jpg', 47400.00, 0, 1),
    (112, 'Creed Love in White', 'Top: Orange Peel. Heart: Iris, Narcissus, Magnolia, Rice. Base: Sandalwood, Vanilla, Ambergris.', 'A pure, clean, and elegant white floral bouquet.', '75 ml', 10, 'creed_love_in_white.jpg', 43200.00, 0, 1),
    (113, 'Rasasi Fattan', 'Top: Grapefruit, Bergamot, Pink Pepper. Heart: Vetiver, Cedar, Patchouli. Base: Oakmoss, Benzoin, Amber.', 'A beautiful, earthy vetiver bomb with excellent performance.', '50 ml', 25, 'rasasi_fattan.jpg', 3600.00, 0, 1),
    (114, 'Rasasi Shuhrah Pour Homme', 'Top: Tomato Leaf, Freesia, Rose. Heart: Rose, Sandalwood, Cedar, Jasmine. Base: Leather, Agarwood, Oakmoss, Musk, Amber.', 'A unique, loud, and smoky floral leather fragrance.', '90 ml', 18, 'rasasi_shuhrah_pour_homme.jpg', 4200.00, 0, 1),
    (115, 'Rasasi La Yuqawam Jasmine Wisp', 'Top: Mandarin Orange, Grapefruit, Lemon. Heart: Passionfruit, White Flowers, Peach. Base: Vanilla, Tonka Bean, Amber.', 'A sweet, fruity, and vanilla delight for women.', '75 ml', 12, 'rasasi_la_yuqawam_jasmine_wisp.jpg', 9000.00, 0, 1),
    (116, 'Rasasi Al Wisam Day', 'Top: Bergamot, Lavender, Geranium. Heart: Rose, Clary Sage, Sandalwood, Cedar. Base: Amber, Musk, Oakmoss, Agarwood.', 'A sparkling, metallic rose and tea scent that feels incredibly fresh.', '100 ml', 20, 'rasasi_al_wisam_day.jpg', 5400.00, 0, 1),
    (117, 'Rasasi Hawas For Her', 'Top: Apple, Grapefruit, Pomegranate. Heart: Iris, Citrus, Jasmine Sambac. Base: Praline, Patchouli, Vetiver.', 'A deliciously fruity and floral scent with a praline dry down.', '100 ml', 15, 'rasasi_hawas_for_her.jpg', 6000.00, 0, 1),
    (118, 'Yves Saint Laurent L Homme', 'Top: Ginger, Bergamot, Lemon. Heart: Spices, White Pepper, Basil. Base: Tonka Bean, Cedar, Tahitian Vetiver.', 'A versatile, smooth, and elegant ginger-spiced everyday fragrance.', '100 ml', 20, 'yves_saint_laurent_l_homme.jpg', 12000.00, 0, 1),
    (119, 'Yves Saint Laurent Libre', 'Top: Lavender, Mandarin Orange, Black Currant. Heart: Lavender, Orange Blossom, Jasmine. Base: Madagascar Vanilla, Musk, Cedar, Ambergris.', 'A bold and empowering blend of French lavender and Moroccan orange blossom.', '90 ml', 30, 'yves_saint_laurent_libre.jpg', 15600.00, 0, 1),
    (120, 'Yves Saint Laurent Y Le Parfum', 'Top: Apple, Aldehydes, Grapefruit, Ginger. Heart: Sage, Lavender, Geranium. Base: Tonka Bean, Cedar, Olibanum.', 'A darker, more intense and mysterious take on the Y DNA.', '100 ml', 18, 'yves_saint_laurent_y_le_parfum.jpg', 17400.00, 0, 1),
    (121, 'Yves Saint Laurent Opium', 'Top: Coriander, Pepper, Clove, Plum. Heart: Carnation, Sandalwood, Patchouli, Cinnamon. Base: Myrrh, Tolu Balsam, Sandalwood.', 'A legendary oriental masterpiece.', '90 ml', 10, 'yves_saint_laurent_opium.jpg', 14400.00, 0, 1),
    (122, 'Yves Saint Laurent Tuxedo', 'Top: Violet Leaf, Coriander, Bergamot. Heart: Rose, Black Pepper, Lily-of-the-Valley. Base: Patchouli, Ambergris, Bourbon Vanilla.', 'A sophisticated, spicy patchouli fragrance. The scent of a sharp black suit.', '125 ml', 8, 'yves_saint_laurent_tuxedo.jpg', 30000.00, 0, 1),
    (123, 'Salvatore Ferragamo Uomo', 'Top: Cardamom, Black Pepper, Bergamot. Heart: Sweet Notes, Ambroxan. Base: Tonka Bean, Sandalwood, Cashmere Wood.', 'A gourmand coffee-tiramisu vibe wrapped in a warm woody base.', '100 ml', 15, 'salvatore_ferragamo_uomo.jpg', 10200.00, 0, 1),
    (124, 'Salvatore Ferragamo Uomo Signature', 'Top: Pink Pepper, Italian Mandarin, Grapefruit. Heart: Cinnamon, Cardamom, Cypress. Base: Tonka Bean, Leather, Roasted Coffee Beans.', 'A darker, leathery take on the tiramisu DNA of the original.', '100 ml', 18, 'salvatore_ferragamo_uomo_signature.jpg', 10800.00, 0, 1),
    (125, 'Salvatore Ferragamo F by Ferragamo Pour Homme', 'Top: Apple, Lavender. Heart: Black Pepper. Base: Leather, Amber, Labdanum.', 'A versatile and fresh spicy apple fragrance.', '100 ml', 14, 'salvatore_ferragamo_f_by_ferragamo_pour_homme.jpg', 7200.00, 0, 1),
    (126, 'Salvatore Ferragamo Signorina', 'Top: Red Currant, Pink Pepper. Heart: Rose, Peony, Jasmine. Base: Panacotta, Musk, Patchouli.', 'A chic, romantic, and slightly sweet gourmand floral.', '100 ml', 20, 'salvatore_ferragamo_signorina.jpg', 10200.00, 0, 1),
    (127, 'Salvatore Ferragamo Acqua Essenziale Blu', 'Top: Lemon, Bergamot, Cardamom. Heart: Lavender, Cypriol Oil. Base: Tonka Bean, Ambroxan, Patchouli.', 'A blue fragrance with a creamy, ambery drydown.', '100 ml', 22, 'salvatore_ferragamo_acqua_essenziale_blu.jpg', 7800.00, 0, 1),
    (128, 'Salvatore Ferragamo Ferragamo Intense Leather', 'Top: Mandarin Orange, Pink Pepper. Heart: Red Apple, Iris, Lily-of-the-Valley. Base: Leather, Earthy Notes, Oakmoss, Musk.', 'A modern, clean, and elegant leather fragrance.', '100 ml', 16, 'salvatore_ferragamo_ferragamo_intense_leather.jpg', 11400.00, 0, 1);
ON CONFLICT (id) DO NOTHING;

-- Keep the identity sequence ahead of the ids inserted above.
SELECT setval(pg_get_serial_sequence('perfumes', 'id'), (SELECT MAX(id) FROM perfumes));

COMMIT;
