"""
Verification harness for the reconstructed Perfume Store database.

Loads postgres/01_schema.sql + _seed_body.sql into an in-memory SQLite
database (with foreign keys enforced) and asserts that the reconstruction
is internally consistent AND consistent with what the PHP source expects.

Run:  python database/verify.py
"""
import io, os, re, sqlite3, sys

HERE = os.path.dirname(os.path.abspath(__file__))
IMAGES = os.path.join(HERE, os.pardir, "images")

failures, checks = [], 0


def check(label, ok, detail=""):
    global checks
    checks += 1
    if ok:
        print("  PASS  " + label)
    else:
        print("  FAIL  " + label + ("  -> " + detail if detail else ""))
        failures.append(label)


def to_sqlite(ddl):
    """Minimal Postgres -> SQLite translation, enough to execute the schema."""
    ddl = ddl[: ddl.index("CREATE OR REPLACE FUNCTION")]      # drop plpgsql trigger
    ddl = re.sub(r"INTEGER\s+GENERATED BY DEFAULT AS IDENTITY", "INTEGER", ddl)
    ddl = re.sub(r"TIMESTAMPTZ", "TEXT", ddl)
    ddl = re.sub(r"NUMERIC\(10,2\)", "REAL", ddl)
    ddl = re.sub(r"\bNOW\(\)", "CURRENT_TIMESTAMP", ddl)
    ddl = re.sub(r"DROP TABLE IF EXISTS (\w+)\s+CASCADE", r"DROP TABLE IF EXISTS \1", ddl)
    return ddl


def main():
    schema = io.open(os.path.join(HERE, "postgres", "01_schema.sql"), encoding="utf-8").read()
    seed = io.open(os.path.join(HERE, "_seed_body.sql"), encoding="utf-8").read()

    db = sqlite3.connect(":memory:")
    db.execute("PRAGMA foreign_keys = ON")

    print("\n[1] Schema and seed execute cleanly with foreign keys enforced")
    try:
        db.executescript(to_sqlite(schema))
        check("schema loads", True)
    except Exception as e:
        check("schema loads", False, str(e))
        return report()
    try:
        db.executescript(seed)
        check("seed loads (all FKs, UNIQUEs and CHECKs satisfied)", True)
    except Exception as e:
        check("seed loads (all FKs, UNIQUEs and CHECKs satisfied)", False, str(e))
        return report()

    viol = db.execute("PRAGMA foreign_key_check").fetchall()
    check("no foreign key violations after seeding", not viol, str(viol))

    print("\n[2] Every table has a primary key and the expected relationships")
    tables = ["customer", "perfumes", "cart", "orders", "order_item"]
    for t in tables:
        pk = [c for c in db.execute("PRAGMA table_info(%s)" % t) if c[5]]
        check("%-11s has a PRIMARY KEY (%s)" % (t, ", ".join(c[1] for c in pk)), len(pk) == 1)

    expected_fks = {
        "cart":       {("user_id", "customer"), ("perfume_id", "perfumes")},
        "orders":     {("user_id", "customer")},
        "order_item": {("order_id", "orders"), ("perfume_id", "perfumes")},
    }
    for t, want in expected_fks.items():
        got = {(r[3], r[2]) for r in db.execute("PRAGMA foreign_key_list(%s)" % t)}
        check("%-11s foreign keys %s" % (t, sorted(want)), got == want, "got %s" % sorted(got))

    print("\n[3] Referential integrity of the seeded rows")
    orphans = [
        ("cart -> customer",       "SELECT COUNT(*) FROM cart c LEFT JOIN customer u ON c.user_id=u.id WHERE u.id IS NULL"),
        ("cart -> perfumes",       "SELECT COUNT(*) FROM cart c LEFT JOIN perfumes p ON c.perfume_id=p.id WHERE p.id IS NULL"),
        ("orders -> customer",     "SELECT COUNT(*) FROM orders o LEFT JOIN customer u ON o.user_id=u.id WHERE u.id IS NULL"),
        ("order_item -> orders",   "SELECT COUNT(*) FROM order_item i LEFT JOIN orders o ON i.order_id=o.id WHERE o.id IS NULL"),
        ("order_item -> perfumes", "SELECT COUNT(*) FROM order_item i LEFT JOIN perfumes p ON i.perfume_id=p.id WHERE p.id IS NULL"),
    ]
    for label, q in orphans:
        n = db.execute(q).fetchone()[0]
        check("no orphan rows: %s" % label, n == 0, "%d orphans" % n)

    print("\n[4] Business rules the PHP relies on")
    bad = db.execute(
        "SELECT o.id, o.total_price, ROUND(SUM(i.price*i.perfume_qty),2) "
        "FROM orders o JOIN order_item i ON i.order_id=o.id "
        "GROUP BY o.id, o.total_price HAVING o.total_price <> ROUND(SUM(i.price*i.perfume_qty),2)"
    ).fetchall()
    check("orders.total_price equals the sum of its order_item lines", not bad, str(bad))

    n = db.execute("SELECT COUNT(*) FROM orders WHERE status NOT BETWEEN 0 AND 4").fetchone()[0]
    check("every orders.status is a valid code 0-4", n == 0)

    n = db.execute("SELECT COUNT(*) FROM customer WHERE admin_check=1").fetchone()[0]
    check("at least one admin account exists (admin_check = 1)", n >= 1, "%d found" % n)

    n = db.execute("SELECT COUNT(*) FROM perfumes WHERE trending=1 AND status=1").fetchone()[0]
    check("home-page carousel has trending published perfumes", n > 0, "%d found" % n)

    n = db.execute("SELECT COUNT(*) FROM (SELECT name FROM perfumes GROUP BY name HAVING COUNT(*)>1)").fetchone()[0]
    check("perfume names are unique (display-perfume.php?name= resolves one row)", n == 0)

    print("\n[5] Brand pages return products (name LIKE filters in brandsearchfunctions.php)")
    for brand, pattern in [
        ("Dior", "%dior%"), ("Chanel", "%chanel%"), ("Lattafa", "%lattafa%"),
        ("Mancera", "%mancera%"), ("Tom Ford", "%tom%ford%"), ("Hugo Boss", "%hugo%boss%"),
    ]:
        n = db.execute(
            "SELECT COUNT(*) FROM perfumes WHERE status=1 AND LOWER(name) LIKE ?", (pattern,)
        ).fetchone()[0]
        check("%-9s brand page returns %d product(s)" % (brand, n), n > 0)

    print("\n[6] Every image_path points at a file that exists in /images")
    missing = [
        r[0] for r in db.execute("SELECT image_path FROM perfumes")
        if not os.path.isfile(os.path.join(IMAGES, r[0]))
    ]
    check("all %d image_path values resolve" % db.execute("SELECT COUNT(*) FROM perfumes").fetchone()[0],
          not missing, "missing: %s" % missing)

    unused = sorted(set(os.listdir(IMAGES)) - {r[0] for r in db.execute("SELECT image_path FROM perfumes")})
    check("no image file is left without a catalogue row", not unused, "unused: %s" % unused)

    print("\n[7] Delete rules behave as designed")
    db.execute("DELETE FROM cart WHERE perfume_id=8")
    try:
        db.execute("DELETE FROM perfumes WHERE id=8")   # id 8 is on order 3
        check("hard-deleting a sold perfume is blocked (RESTRICT)", False, "delete succeeded")
    except sqlite3.IntegrityError:
        check("hard-deleting a sold perfume is blocked (RESTRICT)", True)
    db.rollback()

    before = db.execute("SELECT COUNT(*) FROM order_item WHERE order_id=1").fetchone()[0]
    db.execute("DELETE FROM orders WHERE id=1")
    after = db.execute("SELECT COUNT(*) FROM order_item WHERE order_id=1").fetchone()[0]
    check("deleting an order cascades to its order_item lines", before > 0 and after == 0)
    db.rollback()

    return report()


def report():
    print("\n" + "=" * 62)
    if failures:
        print("%d of %d checks FAILED:" % (len(failures), checks))
        for f in failures:
            print("  - " + f)
        return 1
    print("All %d checks passed." % checks)
    return 0


if __name__ == "__main__":
    sys.exit(main())
