"""
Verification harness for the reconstructed Perfume Store database.

Loads postgres/01_schema.sql + _seed_body.sql into an in-memory SQLite
database (with foreign keys enforced) and asserts that the reconstruction
is internally consistent AND consistent with what the PHP source expects.

Run:  python database/verify.py
"""
import io, os, re, sqlite3, sys

HERE = os.path.dirname(os.path.abspath(__file__))
IMAGES = os.path.join(HERE, os.pardir, "images")

failures, checks = [], 0


def check(label, ok, detail=""):
    global checks
    checks += 1
    if ok:
        print("  PASS  " + label)
    else:
        print("  FAIL  " + label + ("  -> " + detail if detail else ""))
        failures.append(label)


def to_sqlite(ddl):
    """Minimal Postgres -> SQLite translation, enough to execute the schema."""
    ddl = ddl[: ddl.index("CREATE OR REPLACE FUNCTION")]      # drop plpgsql trigger
    ddl = re.sub(r"INTEGER\s+GENERATED BY DEFAULT AS IDENTITY", "INTEGER", ddl)
    ddl = re.sub(r"TIMESTAMPTZ", "TEXT", ddl)
    ddl = re.sub(r"NUMERIC\(10,2\)", "REAL", ddl)
    ddl = re.sub(r"\bNOW\(\)", "CURRENT_TIMESTAMP", ddl)
    ddl = re.sub(r"DROP TABLE IF EXISTS (\w+)\s+CASCADE", r"DROP TABLE IF EXISTS \1", ddl)
    return ddl


def main():
    schema = io.open(os.path.join(HERE, "postgres", "01_schema.sql"), encoding="utf-8").read()
    seed = io.open(os.path.join(HERE, "_seed_body.sql"), encoding="utf-8").read()

    db = sqlite3.connect(":memory:")
    db.execute("PRAGMA foreign_keys = ON")

    print("\n[1] Schema and seed execute cleanly with foreign keys enforced")
    try:
        db.executescript(to_sqlite(schema))
        check("schema loads", True)
    except Exception as e:
        check("schema loads", False, str(e))
        return report()
    try:
        db.executescript(seed)
        check("seed loads (all FKs, UNIQUEs and CHECKs satisfied)", True)
    except Exception as e:
        check("seed loads (all FKs, UNIQUEs and CHECKs satisfied)", False, str(e))
        return report()

    # The expansion seed must apply cleanly on top of the base seed: no id
    # collisions, no duplicate names, every foreign key still satisfied.
    exp_path = os.path.join(HERE, "mysql", "03_seed_expansion.sql")
    if os.path.isfile(exp_path):
        exp = re.sub(r"ALTER TABLE[^;]+;", "",
                     io.open(exp_path, encoding="utf-8").read())
        try:
            db.executescript(exp)
            total = db.execute("SELECT COUNT(*) FROM perfumes").fetchone()[0]
            check("expansion seed applies on top of the base seed (%d products)" % total, True)
        except Exception as e:
            check("expansion seed applies on top of the base seed", False, str(e))

    viol = db.execute("PRAGMA foreign_key_check").fetchall()
    check("no foreign key violations after seeding", not viol, str(viol))

    print("\n[2] Every table has a primary key and the expected relationships")
    tables = ["customer", "perfumes", "cart", "orders", "order_item"]
    for t in tables:
        pk = [c for c in db.execute("PRAGMA table_info(%s)" % t) if c[5]]
        check("%-11s has a PRIMARY KEY (%s)" % (t, ", ".join(c[1] for c in pk)), len(pk) == 1)

    expected_fks = {
        "cart":       {("user_id", "customer"), ("perfume_id", "perfumes")},
        "orders":     {("user_id", "customer")},
        "order_item": {("order_id", "orders"), ("perfume_id", "perfumes")},
    }
    for t, want in expected_fks.items():
        got = {(r[3], r[2]) for r in db.execute("PRAGMA foreign_key_list(%s)" % t)}
        check("%-11s foreign keys %s" % (t, sorted(want)), got == want, "got %s" % sorted(got))

    print("\n[3] Referential integrity of the seeded rows")
    orphans = [
        ("cart -> customer",       "SELECT COUNT(*) FROM cart c LEFT JOIN customer u ON c.user_id=u.id WHERE u.id IS NULL"),
        ("cart -> perfumes",       "SELECT COUNT(*) FROM cart c LEFT JOIN perfumes p ON c.perfume_id=p.id WHERE p.id IS NULL"),
        # user_id is nullable (a guest checkout with no account), so a NULL
        # is a valid non-reference, not an orphan -- only a *set* user_id
        # that fails to match a real customer counts.
        ("orders -> customer",     "SELECT COUNT(*) FROM orders o LEFT JOIN customer u ON o.user_id=u.id WHERE o.user_id IS NOT NULL AND u.id IS NULL"),
        ("order_item -> orders",   "SELECT COUNT(*) FROM order_item i LEFT JOIN orders o ON i.order_id=o.id WHERE o.id IS NULL"),
        ("order_item -> perfumes", "SELECT COUNT(*) FROM order_item i LEFT JOIN perfumes p ON i.perfume_id=p.id WHERE p.id IS NULL"),
    ]
    for label, q in orphans:
        n = db.execute(q).fetchone()[0]
        check("no orphan rows: %s" % label, n == 0, "%d orphans" % n)

    print("\n[4] Business rules the PHP relies on")
    bad = db.execute(
        "SELECT o.id, o.total_price, ROUND(SUM(i.price*i.perfume_qty),2) "
        "FROM orders o JOIN order_item i ON i.order_id=o.id "
        "GROUP BY o.id, o.total_price HAVING o.total_price <> ROUND(SUM(i.price*i.perfume_qty),2)"
    ).fetchall()
    check("orders.total_price equals the sum of its order_item lines", not bad, str(bad))

    n = db.execute("SELECT COUNT(*) FROM orders WHERE status NOT BETWEEN 0 AND 4").fetchone()[0]
    check("every orders.status is a valid code 0-4", n == 0)

    n = db.execute("SELECT COUNT(*) FROM customer WHERE admin_check=1").fetchone()[0]
    check("at least one admin account exists (admin_check = 1)", n >= 1, "%d found" % n)

    n = db.execute("SELECT COUNT(*) FROM perfumes WHERE trending=1 AND status=1").fetchone()[0]
    check("home-page carousel has trending published perfumes", n > 0, "%d found" % n)

    n = db.execute("SELECT COUNT(*) FROM (SELECT name FROM perfumes GROUP BY name HAVING COUNT(*)>1)").fetchone()[0]
    check("perfume names are unique (display-perfume.php?name= resolves one row)", n == 0)

    print("\n[5] Every brand page in the registry returns products")
    helpers = io.open(os.path.join(HERE, os.pardir, "includes", "helpers.php"),
                      encoding="utf-8").read()
    reg = helpers[helpers.index("function brandList()"):helpers.index("function brandBySlug")]
    brands = re.findall(
        r"'([a-z]+)' => \['label' => '([^']+)', 'pattern' => '([^']+)'", reg)
    check("brand registry parsed from includes/helpers.php", len(brands) > 0,
          "%d houses" % len(brands))

    empty = []
    for slug, label, pattern in brands:
        n = db.execute(
            "SELECT COUNT(*) FROM perfumes WHERE status=1 AND LOWER(name) LIKE ?",
            (pattern.lower(),)).fetchone()[0]
        if n == 0:
            empty.append("%s [%s]" % (label, pattern))
    check("all %d brand pages have at least one product" % len(brands),
          not empty, "empty: " + ", ".join(empty))

    # A page file must exist for every registry entry, and vice versa.
    brand_dir = os.path.join(HERE, os.pardir, "brands")
    on_disk = {f[:-4] for f in os.listdir(brand_dir) if f.endswith(".php")}
    in_reg = {s for s, _l, _p in brands}
    check("brands/ has exactly one page per registered house",
          on_disk == in_reg,
          "only on disk: %s | only in registry: %s"
          % (sorted(on_disk - in_reg), sorted(in_reg - on_disk)))

    print("\n[6] Photography")
    # An empty image_path is deliberate: the product has no photograph yet and
    # renders the "photography pending" tile. A non-empty one must resolve.
    paths = [r[0] for r in db.execute("SELECT image_path FROM perfumes")]
    named = [p for p in paths if p.strip()]
    pending = len(paths) - len(named)
    missing = [p for p in named if not os.path.isfile(os.path.join(IMAGES, p))]
    check("all %d named image_path values resolve" % len(named), not missing,
          "missing: %s" % missing)
    check("%d product(s) awaiting photography render the pending tile" % pending, True)

    # No product may carry a photograph of a different house's bottle. The
    # st_ files are the only shared ones, and each is either unbranded or
    # matched to its own house, so assert that mapping has not drifted.
    BRANDED = {
        "st_turquoise_flacon.jpg": "versace",
        "st_black_monolith.jpg":   "prada",
        "st_noir_sparkle.jpg":     "saint laurent",
        "st_minimal_white.jpg":    "armani",
    }
    wrong = []
    for img, house in BRANDED.items():
        for (name,) in db.execute("SELECT name FROM perfumes WHERE image_path = ?", (img,)):
            if house not in name.lower():
                wrong.append("%s on %s" % (img, name))
    check("no product shows another house's bottle", not wrong, "; ".join(wrong))

    unused = sorted(set(os.listdir(IMAGES)) - {r[0] for r in db.execute("SELECT image_path FROM perfumes")})
    check("no image file is left without a catalogue row", not unused, "unused: %s" % unused)

    print("\n[7] Delete rules behave as designed")
    db.execute("DELETE FROM cart WHERE perfume_id=8")
    try:
        db.execute("DELETE FROM perfumes WHERE id=8")   # id 8 is on order 3
        check("hard-deleting a sold perfume is blocked (RESTRICT)", False, "delete succeeded")
    except sqlite3.IntegrityError:
        check("hard-deleting a sold perfume is blocked (RESTRICT)", True)
    db.rollback()

    before = db.execute("SELECT COUNT(*) FROM order_item WHERE order_id=1").fetchone()[0]
    db.execute("DELETE FROM orders WHERE id=1")
    after = db.execute("SELECT COUNT(*) FROM order_item WHERE order_id=1").fetchone()[0]
    check("deleting an order cascades to its order_item lines", before > 0 and after == 0)
    db.rollback()

    return report()


def report():
    print("\n" + "=" * 62)
    if failures:
        print("%d of %d checks FAILED:" % (len(failures), checks))
        for f in failures:
            print("  - " + f)
        return 1
    print("All %d checks passed." % checks)
    return 0


if __name__ == "__main__":
    sys.exit(main())
